RedditClone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:new, :edit, :create, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:delete]
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

RedditClone/app/models/sub.rb
class Sub < ApplicationRecord

  validates :title, :moderator_id, presence: true

  belongs_to :moderator, 
    foreign_key: :moderator_id, 
    primary_key: :id,
    class_name: :User

end

RedditClone/app/models/user.rb
class User < ApplicationRecord

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  attr_reader :password
  before_validation :ensure_session_token

  has_many :moderated_subs,
    foreign_key: :moderator_id,
    primary_key: :id,
    class_name: :Sub,
    inverse_of: :moderator,
    dependent: :destroy

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    if @user && @user.is_password?(password)
      @user
    else
      nil
    end
  end

  def is_password?(password)
    bcrypt_obj = BCrypt::Password.new(self.password_digest)
    bcrypt_obj.is_password?(password)
  end

  def generate_unique_session_token
    token = SecureRandom::urlsafe_base64
    while User.exists?(session_token: token)
      token = SecureRandom::urlsafe_base64
    end
    token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?


    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        @current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

        if @user
            login!(@user)
            redirect_to subs_url
        else
            flash.now[:errors] = ["Invalid Credentials"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :require_logged_in
  before_action :ensure_user_is_moderator, only: [:edit]
  

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to subs_url
    else  
      flash.now[:messages] = ["Invalid Update"]
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  private

  def ensure_user_is_moderator
    @page_sub = Sub.find(params[:id])
    redirect_to subs_url unless @page_sub.moderator_id == current_user.id
  end

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit 
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  # def index
  #   @users = User.all
  #   render :index
  # end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:messages] = ["#{@user} destroyed!!!"]
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper

    def auth_token
        "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
    end
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
<% if logged_in? %>
  <ul>
    <li><%= current_user.username %></li>
    <li><a href="<%= new_sub_url %>">Create a sub!</a></li>
    <li><a href="<%= subs_url %>">All Subs</a></li>
    <li>
      <form action="<%= session_url %>" method="POST">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Logout">
      </form>
    </li>
  </ul>
<% else %>
  <p><a href="<%= new_session_url %>">Sign In!</a></p>
<% end %>
  <br>

    <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error|%>
        <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>
    
    <% if flash[:messages] %>
    <ul>
      <% flash[:messages].each do |message|%>
        <li><%= message %></li>
      <% end %>
    </ul>
    <% end %> 
  
    <%= yield %>
  </body>
</html>

RedditClone/app/views/subs/edit.html.erb
<h1>Edit sub form</h1>

<%= render "subs/shared/form", sub: @sub, action: :edit %>

RedditClone/app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
    <% @subs.each do |sub| %>
        <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <% end %>
</ul>

RedditClone/app/views/subs/new.html.erb
<h1>Make new sub form</h1>

<%= render "subs/shared/form", sub: @sub, action: :new %>

RedditClone/app/views/subs/shared/_form.html.erb
<% if action == :new %>
<% action_url = subs_url %>
<% action_text = "Create Sub" %>
<% else  %>
<% action_text = "Update Sub" %>
<% action_url = sub_url(sub) %>
<% end %>

<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="title">Title</label>
  <input type="text" id="title" name="sub[title]" value="<%= sub.title %>">
  <label for="description">Description</label>
  <input type="textarea" id="description" name="sub[description]" value="<%= sub.description %>">
  <input type="submit" value="<%= action_text %>">

</form>

RedditClone/app/views/subs/show.html.erb
<h1>
  <%= @sub.title %>
</h1>
<br>

<h4>Description</h4>

<p><%= @sub.description %></p>

<% if @sub.moderator_id == current_user.id %>

<p>
  <a href="<%= edit_sub_url %>">Edit</a>
</p>

<% end %>

RedditClone/app/views/users/edit.html.erb
<h1>Update Users</h1>

<%= render "users/shared/credform", action: :edit, user: @user %>

RedditClone/app/views/users/new.html.erb
<h1>New User!</h1>

<%= render "users/shared/credform", action: :new, user: @user %>

RedditClone/app/views/users/shared/_credform.html.erb
<% if action == :new %>
<% action_text = "Sign Up" %>
<% else  %>
<% action_text = "Update" %>
<% end %>



<form action="<%= users_url %>" method="POST">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="username">Username</label>
  <input type="text" id="username" name="user[username]" value="<%= user.username %>">
  <label for="password">Password</label>
  <input type="password" id="password" name="user[password]" value="<%= user.password %>">
  <input type="submit" value="<%= action_text %>">

</form>

RedditClone/app/views/users/show.html.erb
<h1>Show Page!</h1>